### ISSUE TITLE
Minimum account request length and prevent using parts of sample request notes

### ISSUE THREAD

**Issue by SausageMcSauce** [InternationalScratchWiki/scratch-confirmaccount-v3#159]
What I am suggesting might decrease the amount of obviously rejected account requests.

 A minimum request length (probably around 50-100 characters) would prevent account requests that are too short, which would almost never get accepted (although there might need to be phrase blacklists for different languages). Preventing several phrases from the sample request notes being used would prevent submitting account requests that copy and past sample request notes.

If any of these were to be rejected, it should notify the user that they have not read S:CONTRIB properly and state it is most likely that they will not get accepted.

The only problems I can think of of this is this could be assisting users in writing their request notes a tiny bit (the 1 week delay may or may not help  solve this) and users might modify random characters if they are using the sample request notes.

**Comment by Kenny2github** [comment]
IMO, generally we don't get enough account requests of these types for this to really be useful. Account requests that are too short are easily rejected (and are often handled first, since they take less mental effort than analyzing better written requests). Account requests that copy the sample notes are easily identified since the sample notes use a different (nonexistent) flawed article. I could see this becoming more useful if account request volume ticks up, but otherwise this isn't a priority feature, I'd say.

**Comment by jacob-g** [comment]
Thanks for the suggestion, but per Ken's comments above I don't think this adds much value.
